<#
.SYNOPSIS
    Assembles a complete SVG file from a base SVG and a CSV map file.

.DESCRIPTION
    This script reads a 'base_svg.svg' file and a 'map.csv' data file.
    It parses the CSV data to get the properties for each text label.
    Then, it programmatically creates new <text> elements and injects them into the
    base SVG's XML structure. The final, reconstructed SVG is saved as 'full_keyboard_recreated.svg'.

.NOTES
    - This script requires 'base_svg.svg' and 'map.csv' to be in the same directory.
    - These files are generated by the 'disassemble.ps1' script.
    - Running this script will create/overwrite 'full_keyboard_recreated.svg'.
#>

# --- Configuration ---
$baseSvgPath = Join-Path $PSScriptRoot "base_svg.svg"
$mapDataPath = Join-Path $PSScriptRoot "map.csv"
$outputSvgPath = Join-Path $PSScriptRoot "keyboard-map-tks.svg"

# --- Main Logic ---
try {
    # Resolve paths once so PowerShell cmdlets and .NET Save() use the same files.
    $baseSvgPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($baseSvgPath)
    $mapDataPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($mapDataPath)
    $outputSvgPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($outputSvgPath)

    # Check if the required input files exist
    if (-not (Test-Path $baseSvgPath)) { throw "Base SVG file not found at: $baseSvgPath" }
    if (-not (Test-Path $mapDataPath)) { throw "Map data file not found at: $mapDataPath" }

    # Load the base SVG as an XML document
    $svgXml = [xml](Get-Content -Path $baseSvgPath -Raw)
    
    # The namespace is important for creating new elements correctly.
    $namespace = $svgXml.DocumentElement.NamespaceURI

    # Find the first <g> element in the document to serve as the parent for our new text nodes.
    # This is a reasonable assumption for many SVGs.
    $parentElement = $svgXml.SelectSingleNode("//*[local-name()='g']")
    if (-not $parentElement) {
        # If no <g> is found, fall back to the root <svg> element.
        $parentElement = $svgXml.DocumentElement
        Write-Warning "Could not find a <g> element. Appending text to the root <svg> element."
    }

    # Read the map data as CSV so empty columns and line endings are handled correctly.
    $mapEntries = Import-Csv -Path $mapDataPath
    $requiredColumns = @("Text", "X", "Y", "Fill", "Stroke", "FontSize", "FontFamily", "TextAnchor")
    $actualColumns = @($mapEntries | Select-Object -First 1 | ForEach-Object { $_.PSObject.Properties.Name })
    $missingColumns = $requiredColumns | Where-Object { $_ -notin $actualColumns }
    if ($missingColumns.Count -gt 0) {
        throw "Map data file is missing required column(s): $($missingColumns -join ', ')"
    }

    Write-Host "Reading $($mapEntries.Count) entries from $mapDataPath to rebuild SVG."

    $writtenCount = 0

    # Loop through each row of data in the map file
    foreach ($entry in $mapEntries) {
        # Assign properties to a more readable custom object
        $textData = [PSCustomObject]@{
            Text       = $entry.Text
            X          = $entry.X
            Y          = $entry.Y
            Fill       = $entry.Fill
            Stroke     = $entry.Stroke
            FontSize   = $entry.FontSize
            FontFamily = $entry.FontFamily
            TextAnchor = $entry.TextAnchor
        }

        # Create a new 'text' element in the SVG's namespace
        $textElement = $svgXml.CreateElement("text", $namespace)

        # Set attributes for the new element, only if the value is not empty
        if (-not [string]::IsNullOrWhiteSpace($textData.X)) { $textElement.SetAttribute("x", $textData.X) }
        if (-not [string]::IsNullOrWhiteSpace($textData.Y)) { $textElement.SetAttribute("y", $textData.Y) }
        if (-not [string]::IsNullOrWhiteSpace($textData.Fill)) { $textElement.SetAttribute("fill", $textData.Fill) }
        if (-not [string]::IsNullOrWhiteSpace($textData.Stroke)) { $textElement.SetAttribute("stroke", $textData.Stroke) }
        if (-not [string]::IsNullOrWhiteSpace($textData.FontSize)) { $textElement.SetAttribute("font-size", $textData.FontSize) }
        if (-not [string]::IsNullOrWhiteSpace($textData.FontFamily)) { $textElement.SetAttribute("font-family", $textData.FontFamily) }
        if (-not [string]::IsNullOrWhiteSpace($textData.TextAnchor)) { $textElement.SetAttribute("text-anchor", $textData.TextAnchor) }
        
        # Set the actual text content of the element
        $textElement.InnerText = $textData.Text

        # Append the newly created and configured text element to the parent <g> element
        [void]$parentElement.AppendChild($textElement)
        $writtenCount++
    }

    # Save the fully reconstructed XML object to the final SVG file
    $svgXml.Save($outputSvgPath)
    Write-Host "Successfully assembled the full SVG with $writtenCount text entries: $outputSvgPath"

}
catch {
    Write-Error "An error occurred: $($_.Exception.Message)"
}
